### ISSUE TITLE
code is not replaced by text

### ISSUE THREAD

**Issue by davidgeosharpe** [AndiDittrich/WordPress.Cryptex#5] opened 2018-05-30 11:54 UTC
Our site, ohare.org, has recently been migrated to another hosting company.  The shortcode in our posts is no longer being replaced by Cryptex.  It has been working perfectly for a long time on the previous server.  I've deleted and re-installed with no success.  All the System Info items in Settings are green.  We're using the simplest email protection -- replacement with text -- since we have limited tech skills.  What can we do to restore Cryptex?

**Comment by AndiDittrich** [comment] 2018-05-30 12:21
hi davidgeosharpe,

maybe its issue #4 - a php 7 incompatibility within the shortcode handler. this issue has been fixed in the latest beta version - maybe you can give it a try ?

do you have access to the php error log ? 
can you send me the url of the page ?

best regards, Andi

**Comment by davidgeosharpe** [comment] 2018-05-30 13:14
Thanks so much for taking the time for this!  I'm attaching the error.log from the root directory.  Is the PHP error log somewhere else?  I have full FTP access.
[error_log.txt](https://github.com/AndiDittrich/WordPress.Cryptex/files/2054027/error_log.txt)

**Comment by AndiDittrich** [comment] 2018-05-30 13:22
thank you, it seems to be an error in cryptex..but this shouldn't cause the issue you've mentioned.
i will check this!

did your tried the latest plugin version from github ?

```
[30-May-2018 11:12:45 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in /.../wordpress/wp-content/plugins/cryptex/skltn/SettingsManager.php on line 29
```

**Comment by davidgeosharpe** [comment] 2018-05-30 16:07
I'm trying hard not to waste your time on basics, but  in spite of searching, I can't figure out how to install a beta from github.  I'll be happy to try it once I pass that hurdle.

**Comment by AndiDittrich** [comment] 2018-05-30 16:10
just download the master branch (zip archive) https://github.com/AndiDittrich/WordPress.Cryptex/archive/master.zip

and upload the content to your site: `/wp-content/plugins/cryptex`

**Comment by davidgeosharpe** [comment] 2018-05-30 18:33
Thanks for the basics.  I've installed the beta and still no shortcode replacement.  I've cleared the browser cache.  Here's the System Info from the right margin (I'm noticing that "PNG Support" is listed as "available" rather than "installed" if that's relevant) -- 
PHP Version: 5.6.36
Server Software: Linux
Cryptex Plugin Version: 6.0
GD library: installed
GD version: bundled (2.1.0 compatible) (supported)
PNG support: available
FreeType: available
Font Renderer: FreeType 2
Fonts: 12 fonts found
Cache writeable: true

**Comment by AndiDittrich** [comment] 2018-05-30 18:38
it's ok... i have to harmonize the naming scheme :)

your website is ohare.org right ?
i've noticed that only e-mail shortcodes are used on the contact page - did you enable the shortcode support on the cryptex settings page ? `Settings -> Cryptex -> Advanced -> Miscellaneous` ?

**Comment by davidgeosharpe** [comment] 2018-05-30 20:21
Aha!  I suspected the solution was something simple.  Previously I didn't need to enable the support; this time I do.  And now it works.  I've lost the nice blue font, though.  Thanks for guiding me through this! 
 Should I replace the beta with the standard release?

**Comment by davidgeosharpe** [comment] 2018-05-30 20:35
I spoke (wrote) too soon.  The email tags disappear but the address is not clickable.  That's in Chrome.  And in Edge, the phone number instead of the email address is generated as a link (going nowhere).  The post I'm referring to is the contact info for Cupcake, a rabbit in need of a foster home, on the homepage of ohare.org (below the photos).

**Comment by AndiDittrich** [comment] 2018-05-31 07:46
could you create a test-page/post with some shortcodes on your site ? the following testcases are overriding the global settings to test some image options. it makes it easier for me to see whats going wrong.

btw. you have `W3 Total Cache` enabled. did you cleared the cache each time you've made changes to cryptex ? if not W3 Total Cache will deliver the "old" content without cryptex.
during testing/installing new plugins its strongly recommended to **disable all caching plugins**

**testcase**
please copy&paste them into a private/non-public page

```html
<h2>Shortcode Test</h2>
<ul>
    <li>Std Tld: [cryptex]cryptex@example.com[/cryptex]</li>
    <li>Short Tld: [cryptex]cryptex@example.de[/cryptex]</li>
    <li>Long Tld: [cryptex]cryptex@example.technology[/cryptex]</li>
    <li>Subdomain: [cryptex]user.xxx@mail.company.example.com[/cryptex]</li>
    <li>Subdomain: [cryptex]user.mail@x.ge.com[/cryptex]</li>
    <li>EMail Shortcode: [email]user.mail@x.ge.com[/email]</li>
    <li>GMail Postfix: [email]Hello+service1234@gmail.com[/email]</li>
    <li>Telephone1: [telephone]+12 345 678900000[/telephone]</li>
    <li>Telephone2: [telephone]12345567810[/telephone]</li>
</ul>


<h3>Inline</h3>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
At vero eos et accusam et justo duo dolores et ea rebum. Stet clita [cryptex]user.xxx@mail.company.example.com[/cryptex] kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.At vero eos et accusam et justo duo dolores et ea rebum.
Stet clita kasd gubergren, [cryptex]user.mail@x.ge.com[/cryptex] no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

<h2>Autodetection</h2>
<ul>
    <li>Std Tld: cryptex@example.com</li>
    <li>Short Tld: cryptex@example.de</li>
    <li>Long Tld: cryptex@example.technology</li>
    <li>Subdomain: user.xxx@mail.company.example.com</li>
    <li>Subdomain: user.mail@x.ge.com</li>
    <li>Short: admin@abc.tv</li>
    <li>Short: admin@abc.me</li>
</ul>


<h3>Inline</h3>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd user.xxx@mail.company.example.com gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.At vero eos et accusam et justo duo dolores et ea rebum.
    Stet clita kasd gubergren, no sea user.mail@x.ge.com takimata sanctus est Lorem ipsum dolor sit amet.</p>

<h3>Multiple Mails</h3>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd user.xxx@mail.company.example.com hostmaster@example.com gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.At vero eos et accusam et justo duo dolores et ea rebum.
    Stet clita kasd gubergren, no sea user.mail@x.ge.com takimata sanctus est Lorem ipsum dolor sit amet. Contact: hostmaster@example.com, hostmaster@example.com, hostmaster@example.com</p>

<h3>End of line</h3>
hostmaster@example.com

<h2>Shortcode Attribute Test</h2>
<ul>
    <li>Green: [cryptex color="#11a600"]cryptex@example.com[/cryptex]</li>
    <li>10pt: [cryptex size="10pt"]cryptex@example.de[/cryptex]</li>
    <li>Green+10pt: [cryptex size="10pt" color="#11a600"]cryptex@example.technology[/cryptex]</li>
    <li>Single Image: [cryptex security="1"]user.xxx@mail.company.example.com[/cryptex]</li>
    <li>Text + Orange: [cryptex security="0" color="#a62f00"]user.mail@x.ge.com[/cryptex]</li>
    <li>Multipart+Orange+10pt: [cryptex size="10pt" color="#a62f00" security="2"]cryptex@example.technology[/cryptex]</li>
    <li>Advanced multipart+Orange+10pt: [cryptex size="10pt" color="#a62f00" security="3"]cryptex@example.technology[/cryptex]</li>
    <li>Text + Green + 20px: [cryptex security="0" color="#11a600" size="20px"]user.mail@x.ge.com[/cryptex]</li>
    <li>Single Image + Green: [cryptex security="1" color="#11a600"]user.xxx@mail.company.example.com[/cryptex]</li>
    <li>EMail Shortcode + Orange: [email color="#a62f00"]user.mail@x.ge.com[/email]</li>
    <li>EMail Shortcode + Orange + Single Image: [email color="#a62f00" security="1"]user.mail@x.ge.com[/email]</li>
    <li>Telephone Green: [telephone color="#11a600"]+12 345 678900000[/telephone]</li>
    <li>Telephone Green+15pt: [telephone color="#11a600" size="15pt"]+12 345 678900000[/telephone]</li>
</ul>


<h3>Inline</h3>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
    At vero eos et accusam et justo duo dolores et ea rebum. Stet clita [cryptex security="1"]user.xxx@mail.company.example.com[/cryptex] <strong>(single image)</strong> kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.At vero eos et accusam et justo duo dolores et ea rebum.
    Stet clita kasd gubergren, [cryptex security="0" color="#a62f00"]user.mail@x.ge.com[/cryptex] <strong>(Text + Red)</strong> no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
```

**Comment by davidgeosharpe** [comment] 2018-05-31 12:43
I deactivated W3 Total Cache and refreshed.  No change.  Your test codes have been entered into https://www.ohare.org/wordpress/cryptex-testing/ .  That's a public page, but with no entry links.  The complex coding is clearly an upper-level mind game!

**Comment by davidgeosharpe** [comment] 2018-05-31 12:45
Would having administrative access to ohare.org help?  I don't mind doing that as long as you would describe and explain any changes you made.

**Comment by AndiDittrich** [comment] 2018-05-31 13:26
great, thank you!

the cryptex plugin/image generation generally works but a lot of "cached" images (stored in the cryptex plugin directory are missing). additionally there is not truetype font configured...currently the fallback mode is active (build-in php fonts).

such effects can be caused by a low-level php error. could you send my the current error log ?

**Comment by davidgeosharpe** [comment] 2018-05-31 13:43
Here it is ... 
[error_log.txt](https://github.com/AndiDittrich/WordPress.Cryptex/files/2058433/error_log.txt)

**Comment by AndiDittrich** [comment] 2018-06-02 14:08
hi @davidgeosharpe ,

after some days of debugging i'm unable to reproduce the errors thrown by your webhost (error_log).
at the moment i believe that the issue is related to your hosting environment and not a general error within the Cryptex plugin :(

**Comment by davidgeosharpe** [comment] 2018-06-02 14:56
Thanks so much for your efforts.  I don't have much hope contacting the hosting company (Site5).  They have terrible reviews for support.  But at least we can rule out a problem within Cryptex.  That's a start!

**Comment by davidgeosharpe** [comment] 2018-06-03 20:43
Hi Andi,

Success!  After persistent trial-and-error, the functions are working again.  I had to copy the system fonts into a manually created fonts directory within Cryptex, then set the font family to Arial and change the Font-Color to blue.  All the custom selections had been removed, so I selected "Enable-Hyperlinks" and under Options, selected "Include Cryptex-CSS" and "Include Cryptex-Javascript".  Under Advanced, I selected "Use [email] Shortcode" and "Enable Anti-aliasing".  Now it works, though I still don't know why the migration wiped out all those settings.  Thanks again for all the time and effort you put into our issue, and if anyone else has migration woes like this, I hope our exchange of messages will help them.

**Comment by AndiDittrich** [comment] 2018-06-04 08:11
hi @davidgeosharpe 

that sounds great! maybe some of the serialized plugin configuration was damaged during the migration - this can explain the long list of errors in your log related to the configuration loading

best regards, Andi

**Closed as completed by AndiDittrich** 2018-06-04 08:11 UTC
Labels: validated, environment
